# Importing Required Libraries

In [ ]:
#Importing the Required Libraries
!pip install opencage
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from opencage.geocoder import OpenCageGeocode
from pprint import pprint
from google.colab import drive
drive.mount('/content/drive')

Collecting opencage
  Downloading opencage-3.0.2-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: Requests>=2.31.0 in /usr/local/lib/python3.10/dist-packages (from opencage) (2.32.3)
Collecting backoff>=2.2.1 (from opencage)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: tqdm>=4.66.4 in /usr/local/lib/python3.10/dist-packages (from opencage) (4.66.5)
Requirement already satisfied: certifi>=2024.07.04 in /usr/local/lib/python3.10/dist-packages (from opencage) (2024.8.30)
Requirement already satisfied: aiohttp>=3.10.5 in /usr/local/lib/python3.10/dist-packages (from opencage) (3.10.5)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp>=3.10.5->opencage) (2.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp>=3.10.5->opencage) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp>=3.10.5->opencage) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp>=3.10.5->opencage) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp>=3.10.5->opencage) (6.1.0)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp>=3.10.5->opencage) (1.11.1)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp>=3.10.5->opencage) (4.0.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from Requests>=2.31.0->opencage) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from Requests>=2.31.0->opencage) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from Requests>=2.31.0->opencage) (2.2.3)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.10/dist-packages (from multidict<7.0,>=4.5->aiohttp>=3.10.5->opencage) (4.12.2)
Downloading opencage-3.0.2-py3-none-any.whl (21 kB)
Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Installing collected packages: backoff, opencage
Successfully installed backoff-2.2.1 opencage-3.0.2
Mounted at /content/drive

In [ ]:
#Reading the Database
df = pd.read_csv("Go norquest/")

HTTPError: HTTP Error 401: Unauthorized

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Original Dataset

### Shape
This line of code is used to get the dimensions of the dataset. It returns the number of rows and columns in the DataFrame.

In [ ]:
df.shape

(145114, 46)

### Basic Stats
`describe()` provides a summary of statistical information for the numerical columns in the DataFrame. It includes metrics like count (number of non-null entries), mean (average), standard deviation (how spread out the numbers are), min (minimum value), and max (maximum value) which give insights into the data distribution.

In [ ]:
df.describe()

,days_on_market,dealer_id,dealer_email,vehicle_id,uvc,mileage,price,msrp,model_year,certified,has_leather,has_navigation,price_analysis,wheelbase_from_vin,number_price_changes,distance_to_dealer,location_score
count,145114.000000,1.451140e+05,0.0,145114.000000,1.451140e+05,1.451140e+05,1.451140e+05,145114.000000,145114.000000,145114.000000,145114.0,145114.0,145114.000000,145114.000000,145114.000000,145114.000000,145114.000000
mean,47.810218,1.115641e+07,NaN,513749.054006,2.021818e+09,4.598501e+04,4.786611e+04,51247.428229,2021.361157,0.006602,0.0,0.0,0.082928,3026.472990,3.504782,9.436435,3.010984
std,57.862393,4.389865e+04,NaN,94034.105057,3.557037e+06,6.227304e+04,9.070245e+04,21760.734381,3.542539,0.080983,0.0,0.0,0.275774,559.718857,7.765742,6.226795,2.104691
min,1.000000,1.112677e+07,NaN,66737.000000,1.987160e+09,0.000000e+00,0.000000e+00,0.000000,1987.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,1.230000,0.000000
25%,14.000000,1.112884e+07,NaN,480906.000000,2.020161e+09,1.500000e+01,2.699000e+04,35149.000000,2020.000000,0.000000,0.0,0.0,0.000000,2700.000000,0.000000,6.090000,1.000000
50%,26.000000,1.113164e+07,NaN,558583.000000,2.023360e+09,9.650000e+03,4.190000e+04,48035.000000,2023.000000,0.000000,0.0,0.0,0.000000,2850.000000,1.000000,7.420000,4.000000
75%,59.000000,1.116104e+07,NaN,580271.000000,2.024340e+09,8.011900e+04,6.277025e+04,63045.000000,2024.000000,0.000000,0.0,0.0,0.000000,3342.000000,3.000000,9.400000,5.000000
max,367.000000,1.125746e+07,NaN,599912.000000,2.024960e+09,1.000008e+06,1.309532e+07,315100.000000,2024.000000,1.000000,0.0,0.0,1.000000,5014.000000,154.000000,29.660000,5.000000

### Preview of Data
This line displays the first few rows of the DataFrame (usually the first five rows). It’s a quick way to preview the dataset and understand its structure and some initial values.

In [ ]:
df.head()

,listing_id,listing_heading,listing_type,listing_url,listing_first_date,days_on_market,dealer_id,dealer_name,dealer_street,dealer_city,...,wheelbase_from_vin,drivetrain_from_vin,engine_from_vin,transmission_from_vin,fuel_type_from_vin,number_price_changes,price_history_delimited,distance_to_dealer,location_score,listing_dropoff_date
0,f5b663d2-4896-11ef-a15b-8b4423f1ff08,1987 IROC Z 350 Auto T-Tops,Active,https://www.kijiji.ca/v-cars-trucks/edmonton/1...,7/22/2024 0:00,9,11152931,David T's Camaro & Firebird Auto Center,10611 201 St NW,Edmonton,...,0.0,RWD,5.7L V8 TBI,A,Gas,0,"2024-07-22,11500,230860",9.84,5,NaN
1,a9f565e6-4712-11ef-a23f-79dc25c5e601,NaN,Sold,https://www.redlinemotors.ca/vehicle-details/1...,7/20/2024 0:00,4,11131329,Redlinemotors.Ca,14421 Mark Messier Trail,Edmonton,...,0.0,RWD,5.2L V8,A,Gas,0,"2024-07-20,8700,48905",8.30,5,7/24/2024 0:00
2,03d18c58-253a-11ef-8f33-8905b4a2f000,1989 Cadillac DeVille Sedan FWD,Active,https://www.sweetheartmotor.com/cars/used/1989...,6/7/2024 0:00,54,11161704,Gateway Auto & Rv Sales & Financing Ltd,5404 Gateway Blvd NW,Edmonton,...,0.0,FWD,4.5L V8 DI,A,Gas,0,"2024-06-07,6000,174640",5.71,4,NaN
3,2d12630b-460e-11ee-89c4-e5b3161d4741,1989 Cadillac DeVille Sedan FWD,Active,https://www.sweetheartmotor.com/cars/used/1989...,8/28/2023 0:00,338,11128265,Credit Angels,5404 Gateway Blvd NW,Edmonton,...,0.0,FWD,4.5L V8 DI,A,Gas,4,"2023-08-28,4500,174640:2023-09-13,5900,174640:...",5.71,5,NaN
4,53a8e550-47cd-11ef-8587-f926ecb61035,1989 Camaro IROC 350 Auto T-Top,Active,https://www.kijiji.ca/v-cars-trucks/edmonton/1...,7/21/2024 0:00,10,11152931,David T's Camaro & Firebird Auto Center,10611 201 St NW,Edmonton,...,0.0,RWD,5.7L V8 TBI,A,Gas,0,"2024-07-21,8500,288000",9.84,5,NaN

### Datatypes
This command is typically used to get a quick overview of the data types for all the columns in the dataset, which is helpful for further data cleaning and preparation steps.

In [ ]:
df.dtypes

listing_id                  object
listing_heading             object
listing_type                object
listing_url                 object
listing_first_date          object
days_on_market               int64
dealer_id                    int64
dealer_name                 object
dealer_street               object
dealer_city                 object
dealer_province             object
dealer_postal_code          object
dealer_url                  object
dealer_email               float64
dealer_phone                object
dealer_type                 object
stock_type                  object
vehicle_id                   int64
vin                         object
uvc                          int64
mileage                      int64
price                        int64
msrp                         int64
model_year                   int64
make                        object
model                       object
series                      object
style                       object
certified                    int64
has_leather                  int64
has_navigation               int64
exterior_color              object
exterior_color_category     object
interior_color              object
interior_color_category     object
price_analysis               int64
wheelbase_from_vin         float64
drivetrain_from_vin         object
engine_from_vin             object
transmission_from_vin       object
fuel_type_from_vin          object
number_price_changes         int64
price_history_delimited     object
distance_to_dealer         float64
location_score               int64
listing_dropoff_date        object
dtype: object

# New Dataframe

### Required Features
This line defines a list of column names that are needed for our analysis. These are the specific columns that we want to keep from the larger dataset. Listing these columns helps us to focus on only the relevant data.

In [ ]:
# List of columns we need.
columns = [
    "listing_id",
    "listing_type",
    "listing_first_date",
    "days_on_market",
    "dealer_id",
    "dealer_name",
    "dealer_street",
    "dealer_city",
    "dealer_province",
    "dealer_postal_code",
    "stock_type",
    "vehicle_id",
    "mileage",
    "price",
    "model_year",
    "make",
    "model",
    "style",
    "drivetrain_from_vin",
    "engine_from_vin",
    "transmission_from_vin",
    "fuel_type_from_vin",
    "distance_to_dealer",
    "location_score"
]

### Creating new Dataframe
The line creates a new DataFrame called df_new that includes only the columns listed in the columns list. This step is essentially filtering the original DataFrame (df) to keep only the data we are interested in, making the dataset smaller and more manageable for further analysis.

In [ ]:
df_new = df[columns]

In [ ]:
df_new.head()

,listing_id,listing_type,listing_first_date,days_on_market,dealer_id,dealer_name,dealer_street,dealer_city,dealer_province,dealer_postal_code,...,model_year,make,model,style,drivetrain_from_vin,engine_from_vin,transmission_from_vin,fuel_type_from_vin,distance_to_dealer,location_score
0,f5b663d2-4896-11ef-a15b-8b4423f1ff08,Active,7/22/2024 0:00,9,11152931,David T's Camaro & Firebird Auto Center,10611 201 St NW,Edmonton,AB,T5S 1Y8,...,1987,Chevrolet,Camaro,2D Coupe,RWD,5.7L V8 TBI,A,Gas,9.84,5
1,a9f565e6-4712-11ef-a23f-79dc25c5e601,Sold,7/20/2024 0:00,4,11131329,Redlinemotors.Ca,14421 Mark Messier Trail,Edmonton,AB,T6V 1H4,...,1988,Chrysler,Fifth Avenue,4D Sedan,RWD,5.2L V8,A,Gas,8.30,5
2,03d18c58-253a-11ef-8f33-8905b4a2f000,Active,6/7/2024 0:00,54,11161704,Gateway Auto & Rv Sales & Financing Ltd,5404 Gateway Blvd NW,Edmonton,AB,T6H 1B7,...,1989,Cadillac,DeVille,4D Sedan,FWD,4.5L V8 DI,A,Gas,5.71,4
3,2d12630b-460e-11ee-89c4-e5b3161d4741,Active,8/28/2023 0:00,338,11128265,Credit Angels,5404 Gateway Blvd NW,Edmonton,AB,T6H 1B7,...,1989,Cadillac,DeVille,4D Sedan,FWD,4.5L V8 DI,A,Gas,5.71,5
4,53a8e550-47cd-11ef-8587-f926ecb61035,Active,7/21/2024 0:00,10,11152931,David T's Camaro & Firebird Auto Center,10611 201 St NW,Edmonton,AB,T5S 1Y8,...,1989,Chevrolet,Camaro,2D Coupe,RWD,5.7L V8 TBI,A,Gas,9.84,5

# Data Cleaning

### Checking for Null Values
The `isnull()` function in this block of code checks for missing (null) values in the dataframe df_new and `.sum()` counts the total number of null values for each column, providing a summary of missing data in the dataset.

In [ ]:
#Checking for Null values
print(df_new.isnull().sum())

listing_id               0
listing_type             0
listing_first_date       0
days_on_market           0
dealer_id                0
dealer_name              0
dealer_street            0
dealer_city              0
dealer_province          0
dealer_postal_code       0
stock_type               0
vehicle_id               0
mileage                  0
price                    0
model_year               0
make                     0
model                    0
style                    0
drivetrain_from_vin      0
engine_from_vin          0
transmission_from_vin    0
fuel_type_from_vin       0
distance_to_dealer       0
location_score           0
dtype: int64

###Checking number of unique entries for each city

In [ ]:
df_new["dealer_city"].value_counts()

dealer_city
Edmonton             119541
Sherwood Park         10943
Leduc                  9282
St Albert              2329
Spruce Grove           1346
Fort Saskatchewan       944
Devon                   259
Acheson                 237
Nisku                   233
Name: count, dtype: int64

### Counting number of enteries in each column

In [ ]:

#Creating empty Dictionary
count = {}

#Counting unique values in each column and soring it in Dictionary.
for column in columns:
  count[column] = df_new[column].value_counts().shape[0]

#Printing out the dictionary
for key, value in count.items():
  print(key,"->", value)

listing_id -> 145114
listing_type -> 2
listing_first_date -> 413
days_on_market -> 367
dealer_id -> 356
dealer_name -> 230
dealer_street -> 234
dealer_city -> 9
dealer_province -> 1
dealer_postal_code -> 185
stock_type -> 2
vehicle_id -> 14156
mileage -> 46874
price -> 39651
model_year -> 38
make -> 45
model -> 702
series -> 1630
style -> 664
drivetrain_from_vin -> 4
engine_from_vin -> 974
transmission_from_vin -> 4
fuel_type_from_vin -> 7
distance_to_dealer -> 213
location_score -> 6

### Datatypes in new dataframe

In [ ]:
df_new.dtypes

listing_id                object
listing_type              object
listing_first_date        object
days_on_market             int64
dealer_id                  int64
dealer_name               object
dealer_street             object
dealer_city               object
dealer_province           object
dealer_postal_code        object
stock_type                object
vehicle_id                 int64
mileage                    int64
price                      int64
model_year                 int64
make                      object
model                     object
series                    object
style                     object
drivetrain_from_vin       object
engine_from_vin           object
transmission_from_vin     object
fuel_type_from_vin        object
distance_to_dealer       float64
location_score             int64
dtype: object

# Converting postal codes to latitude and longitude

In [ ]:
#Getting the list of postal o=codes
postal_codes = list(df_new["dealer_postal_code"].unique())

In [ ]:
print(len(postal_codes))
print(postal_codes)

185
['T5S 1Y8', 'T6V 1H4', 'T6H 1B7', 'T6X 1A1', 'T8N 7X1', 'T5L 4H5', 'T6E 0G7', 'T8H 2N1', 'T9E 6T9', 'T5V 0C3', 'T5L 5H7', 'T5J 2E5', 'T5J 2R7', 'T5B 2N1', 'T6E 5P2', 'T8H 0X5', 'T8H 0R5', 'T6H 1H1', 'T6E 6A4', 'T6H 4J7', 'T5A 1C3', 'T5Y 3B2', 'T9E 0Z7', 'T6E 5T6', 'T5S 0A2', 'T5E 4C7', 'T5S 1E4', 'T5B 1K3', 'T6E 4C6', 'T6E 5W8', 'T9E 0W8', 'T6E 6V6', 'T5B 1G2', 'T5S 1X2', 'T7X 3A6', 'T5L 4P6', 'T5S 2C3', 'T5R 1Y5', 'T5B 1K2', 'T6E 5P8', 'T9E 7A7', 'T8H 1N1', 'T6H 2K4', 'T5S 1S1', 'T8L 3K8', 'T6B 0G3', 'T5S 1M9', 'T5E 0E2', 'T7X 6A5', 'T6A 3A4', 'T6E 5Z5', 'T5H 0Y5', 'T5H 3K1', 'T6C 4H8', 'T5B 0S4', 'T5G 2Z1', 'T5L 2L5', 'T6V 1J1', 'T9E 7L1', 'T5G 0A8', 'T5C 3C2', 'T5L 2J8', 'T8H 2A2', 'T5S 1B1', 'T6E 6G7', 'T8N 2Y3', 'T6N 1H8', 'T9E 7A9', 'T5S 1A4', 'T5S 1C6', 'T5B 0S9', 'T6W 3G9', 'T6N 1C1', 'T5W 1A8', 'T7X 2Y3', 'T6E 5X9', 'T6K 4E7', 'T5B 4G9', 'T6X 0S8', 'T5G 0H8', 'T6B 2H8', 'T6E 6J6', 'T5G 0B1', 'T5B 1Y2', 'T6E 3J2', 'T8H 1B4', 'T6E 2B1', 'T6E 0X6', 'T6E 0K9', 'T6B 2J8', 'T5G 1R2', 'T6E 4P2', 'T5B 1K1', 'T5S 1R1', 'T5V 1K8', 'T8H 0C7', 'T6J 6V4', 'T5S 1P9', 'T5B 0C4', 'T5W 1G3', 'T5B 1N2', 'T6H 2K8', 'T5S 2A1', 'T6E 5A6', 'T5S 2X1', 'T5E 6M7', 'T5S 0B9', 'T5A 2W9', 'T5G 3E5', 'T6B 0B7', 'T8L 3V5', 'T5S 1N9', 'T8A 4N5', 'T6H 4J8', 'T8H 0E1', 'T5C 0A3', 'T5L 2J7', 'T8N 3Z7', 'T5A 1C2', 'T6W 2P6', 'T5W 1E5', 'T6A 0A7', 'T5E 4C9', 'T5E 1Y8', 'T9E 8A5', 'T6H 5W5', 'T5B 0S6', 'T5S 1N4', 'T5T 3J7', 'T5H 2S8', 'T5S 0A1', 'T8L 0P6', 'T6E 6S9', 'T6E 6L1', 'T6B 2H5', 'T5S 1P5', 'T5M 4G4', 'T5S 2Y4', 'T5S 1B4', 'T9E 7C7', 'T5S 1A7', 'T6V 1H5', 'T6E 5R2', 'T7X 5A3', 'T6B 2T4', 'T6X 1E9', 'T5H 2G1', 'T6E 4W8', 'T6B 2Z9', 'T8H 0M2', 'T5S 2X6', 'T8N 3X9', 'T5S 0J5', 'T6E 6B3', 'T5E 4C4', 'T8N 5A5', 'T5P 4M9', 'T5B 4H8', 'T5M 2R8', 'T5G 0N8', 'T6B 3L9', 'T5S 2C8', 'T6E 4N7', 'T9G 1B2', 'T5L 3C1', 'T6E 5X8', 'T5S 0A8', 'T6H 2H3', 'T6H 5X8', 'T5L 4P3', 'T5H0Y5', 'T5L 2Y6', 'T6H 2J4', 'T6E 6G4', 'T5H2F8', 'T5L 3C5', 'T6C 4A5', 'T9E 0R8', 'T5S 0A6', 'T6W 1A1', 'T5L 2G7', 'T5G 0N9', 'T5S1B4', 'T5S0A1', 'T5S1A7']

In [ ]:
#API key
key = '7dabccf70b6a4501a66b893838e6dd80'
geocoder = OpenCageGeocode(key)

In [ ]:
#Initiating the Dictionary to store latitude and longitude for each postal code
coordinates = {}
for postal_code in postal_codes:
  results = geocoder.geocode(postal_code)
  coordinates[postal_code] = (results[0]['geometry']['lat'],results[0]['geometry']['lng'])

In [ ]:
print(coordinates)

{'T5S 1Y8': (53.549233, -113.666536), 'T6V 1H4': (53.604536, -113.578942), 'T6H 1B7': (53.492482, -113.493143), 'T6X 1A1': (53.421713, -113.48973), 'T8N 7X1': (53.674928, -113.638065), 'T5L 4H5': (53.591185, -113.564813), 'T6E 0G7': (53.499461, -113.483908), 'T8H 2N1': (53.546014, -113.327893), 'T9E 6T9': (53.281782, -113.546323), 'T5V 0C3': (53.576926, -113.589133), 'T5L 5H7': (53.599913, -113.570655), 'T5J 2E5': (53.544736, -113.491391), 'T5J 2R7': (53.521746, -113.466265), 'T5B 2N1': (53.567, -113.464409), 'T6E 5P2': (53.466121, -113.472256), 'T8H 0X5': (53.551967, -113.311705), 'T8H 0R5': (53.556586, -113.310874), 'T6H 1H1': (53.496786, -113.495747), 'T6E 6A4': (53.46741, -113.474281), 'T6H 4J7': (53.48981, -113.493039), 'T5A 1C3': (53.592721, -113.428304), 'T5Y 3B2': (53.599576, -113.417911), 'T9E 0Z7': (53.278779, -113.545601), 'T6E 5T6': (53.466958, -113.471536), 'T5S 0A2': (53.559947, -113.62326), 'T5E 4C7': (53.59468, -113.491331), 'T5S 1E4': (53.542818, -113.625713), 'T5B 1K3': (53.579197, -113.443474), 'T6E 4C6': (53.514708, -113.498031), 'T6E 5W8': (53.465953, -113.477218), 'T9E 0W8': (53.333847, -113.542417), 'T6E 6V6': (53.497962, -113.466073), 'T5B 1G2': (53.582496, -113.481889), 'T5S 1X2': (53.552158, -113.683096), 'T7X 3A6': (53.545537, -113.903261), 'T5L 4P6': (53.592173, -113.568713), 'T5S 2C3': (53.542727, -113.694983), 'T5R 1Y5': (53.520408, -113.589933), 'T5B 1K2': (53.577026, -113.443418), 'T6E 5P8': (53.478324, -113.481022), 'T9E 7A7': (53.274779, -113.547858), 'T8H 1N1': (53.558652, -113.325833), 'T6H 2K4': (53.495635, -113.497162), 'T5S 1S1': (53.542743, -113.631555), 'T8L 3K8': (53.70586, -113.196872), 'T6B 0G3': (53.517728, -113.441163), 'T5S 1M9': (53.543904, -113.630355), 'T5E 0E2': (53.585057, -113.525642), 'T7X 6A5': (53.544574, -113.782322), 'T6A 3A4': (53.542306, -113.444101), 'T6E 5Z5': (53.486069, -113.477623), 'T5H 0Y5': (53.552205, -113.51855), 'T5H 3K1': (53.551929, -113.517376), 'T6C 4H8': (53.511227, -113.441257), 'T5B 0S4': (53.570172, -113.469567), 'T5G 2Z1': (53.582161, -113.492898), 'T5L 2L5': (53.598442, -113.579851), 'T6V 1J1': (53.601613, -113.588422), 'T9E 7L1': (53.289492, -113.54546), 'T5G 0A8': (53.559383, -113.490767), 'T5C 3C2': (53.584064, -113.444293), 'T5L 2J8': (53.570641, -113.532039), 'T8H 2A2': (53.543867, -113.318065), 'T5S 1B1': (53.540351, -113.635669), 'T6E 6G7': (53.468482, -113.489951), 'T8N 2Y3': (53.619324, -113.6077), 'T6N 1H8': (53.455708, -113.474548), 'T9E 7A9': (53.277309, -113.548286), 'T5S 1A4': (53.541938, -113.630124), 'T5S 1C6': (53.539442, -113.638367), 'T5B 0S9': (53.570228, -113.473859), 'T6W 3G9': (53.428507, -113.590232), 'T6N 1C1': (53.46373, -113.468913), 'T5W 1A8': (53.570096, -113.411217), 'T7X 2Y3': (53.54566, -113.9026), 'T6E 5X9': (53.467055, -113.482628), 'T6K 4E7': (53.483413, -113.443877), 'T5B 4G9': (53.573829, -113.460508), 'T6X 0S8': (53.426818, -113.489199), 'T5G 0H8': (53.560534, -113.522931), 'T6B 2H8': (53.513129, -113.407747), 'T6E 6J6': (53.469156, -113.481194), 'T5G 0B1': (53.559035, -113.492552), 'T5B 1Y2': (53.571448, -113.451741), 'T6E 3J2': (53.494776, -113.478623), 'T8H 1B4': (53.554424, -113.319586), 'T6E 2B1': (53.517704, -113.507252), 'T6E 0X6': (53.507795, -113.507911), 'T6E 0K9': (53.50231, -113.488079), 'T6B 2J8': (53.508366, -113.419273), 'T5G 1R2': (53.571235, -113.488478), 'T6E 4P2': (53.498291, -113.459814), 'T5B 1K1': (53.577413, -113.442568), 'T5S 1R1': (53.542936, -113.629053), 'T5V 1K8': (53.577274, -113.586491), 'T8H 0C7': (53.546738, -113.330088), 'T6J 6V4': (53.46246, -113.495135), 'T5S 1P9': (53.542817, -113.63037), 'T5B 0C4': (53.560843, -113.482261), 'T5W 1G3': (53.570648, -113.440594), 'T5B 1N2': (53.580492, -113.444054), 'T6H 2K8': (53.498717, -113.496086), 'T5S 2A1': (53.549727, -113.686217), 'T6E 5A6': (53.489161, -113.474521), 'T5S 2X1': (53.561611, -113.616362), 'T5E 6M7': (53.584443, -113.489058), 'T5S 0B9': (53.54432, -113.641427), 'T5A 2W9': (53.585779, -113.415452), 'T5G 3E5': (53.582625, -113.490243), 'T6B 0B7': (53.513004, -113.441454), 'T8L 3V5': (53.701823, -113.203532), 'T5S 1N9': (53.543524, -113.61727), 'T8A 4N5': (53.513148, -113.325929), 'T6H 4J8': (53.491305, -113.496239), 'T8H 0E1': (53.568231, -113.311384), 'T5C 0A3': (53.58571, -113.443361), 'T5L 2J7': (53.588151, -113.576664), 'T8N 3Z7': (53.625671, -113.637513), 'T5A 1C2': (53.593061, -113.430422), 'T6W 2P6': (53.422385, -113.497227), 'T5W 1E5': (53.570063, -113.431555), 'T6A 0A7': (53.537893, -113.439521), 'T5E 4C9': (53.59329, -113.49307), 'T5E 1Y8': (53.598817, -113.494524), 'T9E 8A5': (53.294746, -113.545184), 'T6H 5W5': (53.48916, -113.491158), 'T5B 0S6': (53.570187, -113.470844), 'T5S 1N4': (53.541463, -113.632697), 'T5T 3J7': (53.522335, -113.622923), 'T5H 2S8': (53.556703, -113.494246), 'T5S 0A1': (53.559087, -113.624689), 'T8L 0P6': (53.674443, -113.242826), 'T6E 6S9': (53.467826, -113.47846), 'T6E 6L1': (53.4683, -113.484201), 'T6B 2H5': (53.509612, -113.415763), 'T5S 1P5': (53.542662, -113.628141), 'T5M 4G4': (53.563623, -113.579631), 'T5S 2Y4': (53.539532, -113.651114), 'T5S 1B4': (53.540342, -113.629705), 'T9E 7C7': (53.282279, -113.546108), 'T5S 1A7': (53.542411, -113.638397), 'T6V 1H5': (53.607832, -113.587096), 'T6E 5R2': (53.478723, -113.477049), 'T7X 5A3': (53.563063, -113.766949), 'T6B 2T4': (53.533363, -113.416531), 'T6X 1E9': (53.422085, -113.474242), 'T5H 2G1': (53.559576, -113.486317), 'T6E 4W8': (53.487292, -113.477167), 'T6B 2Z9': (53.508912, -113.434842), 'T8H 0M2': (53.56693, -113.313956), 'T5S 2X6': (53.540246, -113.64364), 'T8N 3X9': (53.666385, -113.628717), 'T5S 0J5': (53.559002, -113.61948), 'T6E 6B3': (53.469841, -113.480067), 'T5E 4C4': (53.59035, -113.49115), 'T8N 5A5': (53.636964, -113.570135), 'T5P 4M9': (53.539746, -113.612409), 'T5B 4H8': (53.582498, -113.449686), 'T5M 2R8': (53.559574, -113.596458), 'T5G 0N8': (53.570173, -113.487994), 'T6B 3L9': (53.494061, -113.44116), 'T5S 2C8': (53.545649, -113.622794), 'T6E 4N7': (53.502571, -113.450468), 'T9G 1B2': (53.366867, -113.734055), 'T5L 3C1': (53.582383, -113.550417), 'T6E 5X8': (53.466829, -113.475741), 'T5S 0A8': (53.560491, -113.618451), 'T6H 2H3': (53.495249, -113.491547), 'T6H 5X8': (53.490051, -113.496852), 'T5L 4P3': (53.597906, -113.575949), 'T5H0Y5': (53.552205, -113.51855), 'T5L 2Y6': (53.576502, -113.574076), 'T6H 2J4': (53.489435, -113.494305), 'T6E 6G4': (53.496501, -113.463115), 'T5H2F8': (22.4452468, 114.0304155), 'T5L 3C5': (53.582267, -113.572812), 'T6C 4A5': (53.509855, -113.438178), 'T9E 0R8': (53.291928, -113.530521), 'T5S 0A6': (53.558529, -113.638664), 'T6W 1A1': (53.420286, -113.494915), 'T5L 2G7': (53.571387, -113.566433), 'T5G 0N9': (53.570162, -113.489783), 'T5S1B4': (53.540342, -113.629705), 'T5S0A1': (53.559087, -113.624689), 'T5S1A7': (53.542411, -113.638397)}

In [ ]:
#Converting the Dictionary to Dataframe

df_coord = pd.DataFrame(coordinates).T
# Transpose the DataFrame to get the desired format

# Rename the columns
df_coord.columns = ['Latitude', 'Longitude']

# Reset index to make Postal Codes a column
df_coord.reset_index(inplace=True)

# Rename index column to 'Postal Code'
df_coord.rename(columns={'index': 'Postal Code'}, inplace=True)

# Display DataFrame
print(df_coord)

    Postal Code   Latitude   Longitude
0       T5S 1Y8  53.549233 -113.666536
1       T6V 1H4  53.604536 -113.578942
2       T6H 1B7  53.492482 -113.493143
3       T6X 1A1  53.421713 -113.489730
4       T8N 7X1  53.674928 -113.638065
..          ...        ...         ...
180     T5L 2G7  53.571387 -113.566433
181     T5G 0N9  53.570162 -113.489783
182      T5S1B4  53.540342 -113.629705
183      T5S0A1  53.559087 -113.624689
184      T5S1A7  53.542411 -113.638397

[185 rows x 3 columns]

In [ ]:
df_coord.to_csv("dealer_coordinates.csv", index=False)

In [ ]:
# This newdf was created in excel after we obtain all the coordinates (longitude and latitude)
# for all unique Postal Codes in the original dataset. Since are creating a dashboard in PowerBi
# a csv file was needed, and now uploaded in this block

newdf = pd.read_csv("CBB_Listings_LongLat.csv")
newdf

,listing_id,listing_heading,listing_type,listing_url,listing_first_date,days_on_market,dealer_id,dealer_name,dealer_street,dealer_city,...,wheelbase_from_vin,drivetrain_from_vin,engine_from_vin,transmission_from_vin,fuel_type_from_vin,number_price_changes,price_history_delimited,distance_to_dealer,location_score,listing_dropoff_date
0,f5b663d2-4896-11ef-a15b-8b4423f1ff08,1987 IROC Z 350 Auto T-Tops,Active,https://www.kijiji.ca/v-cars-trucks/edmonton/1...,7/22/2024 0:00,9,11152931,David T's Camaro & Firebird Auto Center,10611 201 St NW,Edmonton,...,0.0,RWD,5.7L V8 TBI,A,Gas,0,"2024-07-22,11500,230860",9.84,5,NaN
1,a9f565e6-4712-11ef-a23f-79dc25c5e601,NaN,Sold,https://www.redlinemotors.ca/vehicle-details/1...,7/20/2024 0:00,4,11131329,Redlinemotors.Ca,14421 Mark Messier Trail,Edmonton,...,0.0,RWD,5.2L V8,A,Gas,0,"2024-07-20,8700,48905",8.30,5,7/24/2024 0:00
2,03d18c58-253a-11ef-8f33-8905b4a2f000,1989 Cadillac DeVille Sedan FWD,Active,https://www.sweetheartmotor.com/cars/used/1989...,6/7/2024 0:00,54,11161704,Gateway Auto & Rv Sales & Financing Ltd,5404 Gateway Blvd NW,Edmonton,...,0.0,FWD,4.5L V8 DI,A,Gas,0,"2024-06-07,6000,174640",5.71,4,NaN
3,2d12630b-460e-11ee-89c4-e5b3161d4741,1989 Cadillac DeVille Sedan FWD,Active,https://www.sweetheartmotor.com/cars/used/1989...,8/28/2023 0:00,338,11128265,Credit Angels,5404 Gateway Blvd NW,Edmonton,...,0.0,FWD,4.5L V8 DI,A,Gas,4,"2023-08-28,4500,174640:2023-09-13,5900,174640:...",5.71,5,NaN
4,53a8e550-47cd-11ef-8587-f926ecb61035,1989 Camaro IROC 350 Auto T-Top,Active,https://www.kijiji.ca/v-cars-trucks/edmonton/1...,7/21/2024 0:00,10,11152931,David T's Camaro & Firebird Auto Center,10611 201 St NW,Edmonton,...,0.0,RWD,5.7L V8 TBI,A,Gas,0,"2024-07-21,8500,288000",9.84,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145109,8c4d2cd4-db92-11ee-ab06-77676d6b474c,2024 Volvo XC90 Recharge T8 Ultimate Bright Th...,Sold,https://www.volvocarsedmonton.com/inventory/ne...,3/5/2024 0:00,99,11132447,Volvo Cars Edmonton,1205 101 St SW,Edmonton,...,2984.5,AWD,2.0L I-4 DI PHEV T/C,A,PHEV,25,"2024-03-05,101485,30:2024-03-06,101484,30:2024...",13.33,5,6/12/2024 0:00
145110,8b564927-db92-11ee-8456-d37a8da2f6cb,2024 Volvo XC90 Recharge T8 Ultimate Bright Th...,Sold,https://www.volvocarsedmonton.com/inventory/ne...,3/5/2024 0:00,96,11132447,Volvo Cars Edmonton,1205 101 St SW,Edmonton,...,2984.5,AWD,2.0L I-4 DI PHEV T/C,A,PHEV,22,"2024-03-05,105984,30:2024-03-08,105985,30:2024...",13.33,5,6/9/2024 0:00
145111,474ecb38-0c14-11ef-a6d5-81e7286561b2,2024 Volvo XC90 Recharge T8 Ultimate Bright Th...,Sold,https://www.volvocarsedmonton.com/inventory/ne...,5/6/2024 0:00,22,11132447,Volvo Cars Edmonton,1205 101 St SW,Edmonton,...,2984.5,AWD,2.0L I-4 DI PHEV T/C,A,PHEV,2,"2024-05-06,108201,1943:2024-05-11,10820068,194...",13.33,5,5/28/2024 0:00
145112,7208325d-e725-11ee-bf7d-151c90416979,2024 Volvo XC90 Recharge T8 eAWD PHEV Ultimate...,Sold,https://www.volvocarsedmonton.com/inventory/ne...,3/20/2024 0:00,71,11132447,Volvo Cars Edmonton,1205 101 St SW,Edmonton,...,2984.5,AWD,2.0L I-4 DI PHEV T/C,A,PHEV,10,"2024-03-20,108197,782:2024-04-03,108200,782:20...",13.33,5,5/30/2024 0:00
145113,70f556a5-6bff-4836-97cc-c859d6b88f15,Pre-Owned 2024 Volvo XC90 Recharge Plug-In Hyb...,Sold,https://www.southgateaudi.com/used/Volvo/2024-...,7/20/2024 0:00,4,11204118,Southgate Audi,1235 101 Street SW,Edmonton,...,2984.5,AWD,2.0L I-4 DI PHEV T/C,A,PHEV,0,"2024-07-20,0,9333",13.38,5,7/24/2024 0:00

In [ ]:
newdf['transmission_from_vin'].value_counts()

transmission_from_vin
A    141105
M      3975
7        32
6         2
Name: count, dtype: int64

In [ ]:
newsdf['make'].value_counts()